//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 栗子商城.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class goodsSKUTables
    {
        public int SKUId { get; set; }
        public string SKUGoodName { get; set; }
        public string Goods_Description { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
        public Nullable<int> inventory { get; set; }
        public string GoodPhoto { get; set; }
        public Nullable<int> SPUID { get; set; }
        public string BusinName { get; set; }
        public Nullable<int> onclicknum { get; set; }
    }
}
