//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 栗子商城.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsPhotoTable
    {
        public int PhotoID { get; set; }
        public string Photo_one { get; set; }
        public string Photo_two { get; set; }
        public string Photo_three { get; set; }
        public string Photo_four { get; set; }
        public string Photo_five { get; set; }
        public Nullable<int> SKUId { get; set; }
    }
}
