//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 栗子商城.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class lizishoppingEntities : DbContext
    {
        public lizishoppingEntities()
            : base("name=lizishoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appraise> Appraise { get; set; }
        public virtual DbSet<GoodImg> GoodImg { get; set; }
        public virtual DbSet<GoodsPhotoTable> GoodsPhotoTable { get; set; }
        public virtual DbSet<goodsSKUColor> goodsSKUColor { get; set; }
        public virtual DbSet<goodsSKUTables> goodsSKUTables { get; set; }
        public virtual DbSet<goodsSPUTables> goodsSPUTables { get; set; }
        public virtual DbSet<MangeAdmin> MangeAdmin { get; set; }
        public virtual DbSet<OrderGoodslist> OrderGoodslist { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<ShopCategory> ShopCategory { get; set; }
        public virtual DbSet<ShoppCar> ShoppCar { get; set; }
        public virtual DbSet<shoucang> shoucang { get; set; }
        public virtual DbSet<User_addressTable> User_addressTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    
        public virtual int add_order(Nullable<int> userId, Nullable<int> addressId, Nullable<decimal> total, Nullable<decimal> tranMoney, string payState, string createTime, Nullable<int> sKUId, Nullable<int> goodNum, string goodColorname, Nullable<int> goodPrice)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var addressIdParameter = addressId.HasValue ?
                new ObjectParameter("AddressId", addressId) :
                new ObjectParameter("AddressId", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(decimal));
    
            var tranMoneyParameter = tranMoney.HasValue ?
                new ObjectParameter("TranMoney", tranMoney) :
                new ObjectParameter("TranMoney", typeof(decimal));
    
            var payStateParameter = payState != null ?
                new ObjectParameter("PayState", payState) :
                new ObjectParameter("PayState", typeof(string));
    
            var createTimeParameter = createTime != null ?
                new ObjectParameter("CreateTime", createTime) :
                new ObjectParameter("CreateTime", typeof(string));
    
            var sKUIdParameter = sKUId.HasValue ?
                new ObjectParameter("SKUId", sKUId) :
                new ObjectParameter("SKUId", typeof(int));
    
            var goodNumParameter = goodNum.HasValue ?
                new ObjectParameter("GoodNum", goodNum) :
                new ObjectParameter("GoodNum", typeof(int));
    
            var goodColornameParameter = goodColorname != null ?
                new ObjectParameter("GoodColorname", goodColorname) :
                new ObjectParameter("GoodColorname", typeof(string));
    
            var goodPriceParameter = goodPrice.HasValue ?
                new ObjectParameter("GoodPrice", goodPrice) :
                new ObjectParameter("GoodPrice", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_order", userIdParameter, addressIdParameter, totalParameter, tranMoneyParameter, payStateParameter, createTimeParameter, sKUIdParameter, goodNumParameter, goodColornameParameter, goodPriceParameter);
        }
    
        public virtual int del_orders(Nullable<int> orderid)
        {
            var orderidParameter = orderid.HasValue ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_orders", orderidParameter);
        }
    
        public virtual int insertin(string sPUGoodName, string goodInfo, Nullable<int> shopID)
        {
            var sPUGoodNameParameter = sPUGoodName != null ?
                new ObjectParameter("SPUGoodName", sPUGoodName) :
                new ObjectParameter("SPUGoodName", typeof(string));
    
            var goodInfoParameter = goodInfo != null ?
                new ObjectParameter("GoodInfo", goodInfo) :
                new ObjectParameter("GoodInfo", typeof(string));
    
            var shopIDParameter = shopID.HasValue ?
                new ObjectParameter("ShopID", shopID) :
                new ObjectParameter("ShopID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertin", sPUGoodNameParameter, goodInfoParameter, shopIDParameter);
        }
    
        public virtual ObjectResult<selpro_detial_img_Result> selpro_detial_img(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selpro_detial_img_Result>("selpro_detial_img", idParameter);
        }
    
        public virtual ObjectResult<selpro_detials_id_Result> selpro_detials_id(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selpro_detials_id_Result>("selpro_detials_id", idParameter);
        }
    
        public virtual ObjectResult<selpro_detials_SKUGoodName_Result> selpro_detials_SKUGoodName(string sKUGoodName)
        {
            var sKUGoodNameParameter = sKUGoodName != null ?
                new ObjectParameter("SKUGoodName", sKUGoodName) :
                new ObjectParameter("SKUGoodName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selpro_detials_SKUGoodName_Result>("selpro_detials_SKUGoodName", sKUGoodNameParameter);
        }
    
        public virtual ObjectResult<selpro_pingjia_id_Result> selpro_pingjia_id(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selpro_pingjia_id_Result>("selpro_pingjia_id", idParameter);
        }
    
        public virtual ObjectResult<selpro_zuixin_Result> selpro_zuixin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selpro_zuixin_Result>("selpro_zuixin");
        }
    
        public virtual ObjectResult<selprocart_userid_Result> selprocart_userid(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selprocart_userid_Result>("selprocart_userid", useridParameter);
        }
    
        public virtual ObjectResult<selproorders_all_Result> selproorders_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selproorders_all_Result>("selproorders_all");
        }
    
        public virtual ObjectResult<selproorders_zhuangtai_Result> selproorders_zhuangtai(Nullable<int> userid, string zhuangtai)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var zhuangtaiParameter = zhuangtai != null ?
                new ObjectParameter("zhuangtai", zhuangtai) :
                new ObjectParameter("zhuangtai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selproorders_zhuangtai_Result>("selproorders_zhuangtai", useridParameter, zhuangtaiParameter);
        }
    
        public virtual ObjectResult<selproxaingqing_Result> selproxaingqing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selproxaingqing_Result>("selproxaingqing");
        }
    
        public virtual ObjectResult<selproxiangqing_rexiao_Result> selproxiangqing_rexiao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selproxiangqing_rexiao_Result>("selproxiangqing_rexiao");
        }
    
        public virtual ObjectResult<selspuandshoptype_Result> selspuandshoptype()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selspuandshoptype_Result>("selspuandshoptype");
        }
    
        public virtual ObjectResult<selspuandtype_id_Result> selspuandtype_id(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selspuandtype_id_Result>("selspuandtype_id", idParameter);
        }
    
        public virtual ObjectResult<selspuandtype_top_Result> selspuandtype_top()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selspuandtype_top_Result>("selspuandtype_top");
        }
    }
}
