//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 栗子商城.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_addressTable
    {
        public int AddressId { get; set; }
        public string consigneeName { get; set; }
        public string Adress { get; set; }
        public string postal_code { get; set; }
        public string contact_way { get; set; }
        public Nullable<int> UserId { get; set; }
        public string default_Address { get; set; }
    }
}
